config/routes.rb
Sericard::Application.routes.draw do
  
  resources :requisicoes

  match 'produtos_entrada_path', 'produtos/entrada/', :controller => 'produtos', :action => 'entrada', :via => 'get'
  match 'produtos_saida_path', 'produtos/saida/', :controller => 'produtos', :action => 'saida', :via => 'get'
  match 'produtos_search_path','search/produtos', :controller => 'produtos', :action => 'search', :via => 'get'

  match 'search/lotes/', :controller => 'lotes', :action => 'search', :via => 'get'
  match 'lotes_finalizados_path', 'lotes/finalizados/', :controller => 'lotes', :action => 'finalizados', :via => 'get'
  match 'relatorio/:id/', :controller => 'lotes', :action => 'relatorio', :via => 'get'
  
  devise_for :funcionarios

  resources :produtos
  resources :lotes, :except => [:show]
  resources :operadoras  
  resources :funcionarios

  root :to => "lotes#index"

  

end

app/models/produto.rb
class Produto < ActiveRecord::Base

	validates_presence_of :codigo, :codigo_sericard, :orientador, :edicao, :grade, :estoque_atual, :enderecamento

	paginates_per 30

	scope :default_order, -> {order("codigo_sericard ASC")}
	scope :by_codigo, lambda {|codigo| where("codigo like ?", "#{codigo}")}
	scope :search, lambda {|codigo| where("codigo like ?", "%#{codigo}%")}

  # Pega reposicao
  def reposicao
    reposicao = self.estoque_atual - self.grade
    reposicao
	end	
  
  # Checa se o estoque esta abaixo do nivel de reposicao
	def reposicao?
    if reposicao > 0
      return true
    end
      
    false      
	end

	# Checa se existe produto no estoque
	def estoque?
		return true unless self.estoque_atual < 1
		false
	end	

	# Verifica a cor da row de acordo com o estado de estoque
	def row_class
    
		if reposicao?
      return "success"
		else
      return "error"
		end		

	end



end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all.default_order.page params[:page]
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to produtos_path }
        format.json { render action: 'show', status: :created, location: @produto }
      else
        format.html { render action: 'new' }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to produtos_path }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url }
      format.json { head :no_content }
    end
  end

  def entrada
    @produto = Produto.by_codigo(params[:codigo]).first
    @produto.estoque_atual += params[:quantidade].to_i
    @produto.save

    respond_to do |format|
      format.html { redirect_to produtos_path }
    end
  end
  
  def saida
    @produto = Produto.by_codigo(params[:codigo]).first
    if @produto.estoque? 
      @produto.estoque_atual -= params[:quantidade].to_i
      @produto.save
    end

    respond_to do |format|
      format.html { redirect_to produtos_path }
    end
  end

  def search
    @codigo = params[:codigo]
    @produtos = Produto.search(@codigo).page params[:page]
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:codigo, :codigo_sericard, :orientador, :edicao, :grade, :estoque_atual, :enderecamento)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br>
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :codigo_sericard %><br>
    <%= f.text_field :codigo_sericard %>
  </div>
  <div class="field">
    <%= f.label :orientador %><br>
    <%= f.text_field :orientador %>
  </div>
  <div class="field">
    <%= f.label :edicao %><br>
    <%= f.date_field :edicao %>
  </div>
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.number_field :grade %>
  </div>
  <div class="field">
    <%= f.label :estoque_atual %><br>
    <%= f.number_field :estoque_atual %>
  </div>
  <div class="field">
    <%= f.label :enderecamento %><br>
    <%= f.text_field :enderecamento %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editar produto</h1>

<%= render 'form' %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

app/views/produtos/index.html.erb
<h1>Estoque</h1>

<div class="navbar">
  <div class="navbar-inner">    
    <form class="navbar-search pull-left" action="/search/produtos/" method="get">      
      <input type="text" name="codigo" class="search-query" placeholder="Buscar...">      
    </form>                   
  </div>
</div>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>Código</th>
      <th>Código sericard</th>
      <th>Orientador</th>
      <th>Edição</th>
      <th>Grade</th>
      <th>Estoque atual</th>      
      <th>Reposição</th>
      <th>Endereçamento</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>

       <!-- Modal Entrada -->
            <div id="modal-entrada-<%= produto.codigo %>" style="width: 300px; left: 60%;" class="modal fade hide" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>    
                <h3 id="myModalLabel">Entrada</h3>
              </div>
              
              <form class="navbar-search pull-left" action="/produtos/entrada/" method="get">

                  <div class="modal-body" style="text-align: center;">

                      <div><label for="codigo">Adicionar à <%= produto.codigo %> (Estoque atual: <%= produto.estoque_atual %>)</label></div>
                      <input type="hidden" name="codigo" value="<%= produto.codigo %>">
                      <div><input name="quantidade" type="text" class="search-query" placeholder="Quantidade"></div>

                  </div>
                  <div class="modal-footer"> 
                    <button type="submit" class="btn">Adicionar</button>   
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
                  </div>

              </form>

            </div>
      <!-- Modal Entrada -->

      <!-- Modal Saida -->
            <div id="modal-saida-<%= produto.codigo %>" style="width: 300px; left: 60%;" class="modal fade hide" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>    
                <h3 id="myModalLabel">Saída</h3>
              </div>
              <form class="navbar-search pull-left" action="/produtos/saida/" method="get">

                  <div class="modal-body" style="text-align: center;">

                      <div><label for="codigo">Subtrair de <%= produto.codigo %> (Estoque atual: <%= produto.estoque_atual %>)</label></div>
                      <input type="hidden" name="codigo" value="<%= produto.codigo %>">
                      <div><input name="quantidade" type="text" class="search-query" placeholder="Quantidade"></div>

                  </div>
                  <div class="modal-footer"> 
                    <button type="submit" class="btn">Subtrair</button>   
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
                  </div>

              </form>
            </div>
      <!-- Modal Saida -->


      <tr class="<%= produto.row_class %>">
        <td><a href="javascript:$('#modal-entrada-<%= produto.codigo %>').modal('show');"><i class="icon-plus-sign"></i></a></td>
        <td><a href="javascript:$('#modal-saida-<%= produto.codigo %>').modal('show');"><i class="icon-minus-sign"></i></a></td>
        <td><%= produto.codigo %></td>
        <td><%= produto.codigo_sericard %></td>
        <td><%= produto.orientador %></td>
        <td><%= produto.edicao.strftime("%m/%Y") %></td>
        <td><%= produto.grade %></td>
        <td><%= produto.estoque_atual %></td>
        <td><%= produto.reposicao %></td>
        <td><%= produto.enderecamento %></td>
        <td><%= link_to content_tag(:i, "", class: "icon-edit"), edit_produto_path(produto) %></td>
        <td><%= link_to content_tag(:i, "", class: "icon-trash"), produto, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @produtos %>

app/views/produtos/new.html.erb
<h1>Novo produto</h1>

<%= render 'form' %>

<%= link_to 'Back', produtos_path %>

app/views/produtos/search.html.erb
<h1>Estoque - Busca por <%= @codigo %></h1>

<div class="navbar">
  <div class="navbar-inner">    
    <form class="navbar-search pull-left" action="/search/produtos/" method="get">      
      <input type="text" name="codigo" class="search-query" placeholder="Buscar...">      
    </form>                   
  </div>
</div>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>Código</th>
      <th>Código sericard</th>
      <th>Orientador</th>
      <th>Edição</th>
      <th>Grade</th>
      <th>Estoque atual</th>      
      <th>Reposição</th>
      <th>Endereçamento</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>

      <!-- Modal Entrada -->
            <div id="modal-entrada-<%= produto.codigo %>" style="width: 300px; left: 60%;" class="modal fade hide" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>    
                <h3 id="myModalLabel">Entrada</h3>
              </div>
              
              <form class="navbar-search pull-left" action="/produtos/entrada/" method="get">

                  <div class="modal-body" style="text-align: center;">

                      <div><label for="codigo">Adicionar à <%= produto.codigo %> (Estoque atual: <%= produto.estoque_atual %>)</label></div>
                      <input type="hidden" name="codigo" value="<%= produto.codigo %>">
                      <div><input name="quantidade" type="text" class="search-query" placeholder="Quantidade"></div>

                  </div>
                  <div class="modal-footer"> 
                    <button type="submit" class="btn">Adicionar</button>   
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
                  </div>

              </form>

            </div>
      <!-- Modal Entrada -->

      <!-- Modal Saida -->
            <div id="modal-saida-<%= produto.codigo %>" style="width: 300px; left: 60%;" class="modal fade hide" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>    
                <h3 id="myModalLabel">Saída</h3>
              </div>
              <form class="navbar-search pull-left" action="/produtos/saida/" method="get">

                  <div class="modal-body" style="text-align: center;">

                      <div><label for="codigo">Subtrair de <%= produto.codigo %> (Estoque atual: <%= produto.estoque_atual %>)</label></div>
                      <input type="hidden" name="codigo" value="<%= produto.codigo %>">
                      <div><input name="quantidade" type="text" class="search-query" placeholder="Quantidade"></div>

                  </div>
                  <div class="modal-footer"> 
                    <button type="submit" class="btn">Subtrair</button>   
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
                  </div>

              </form>
            </div>
      <!-- Modal Saida -->

      <tr class="<%= produto.row_class %>">
        <td><a href="javascript:$('#modal-entrada-<%= produto.codigo %>').modal('show');"><i class="icon-plus-sign"></i></a></td>
        <td><a href="javascript:$('#modal-saida-<%= produto.codigo %>').modal('show');"><i class="icon-minus-sign"></i></a></td>
        <td><%= produto.codigo %></td>
        <td><%= produto.codigo_sericard %></td>
        <td><%= produto.orientador %></td>
        <td><%= produto.edicao.strftime("%m/%Y") %></td>
        <td><%= produto.grade %></td>
        <td><%= produto.estoque_atual %></td>
        <td><%= produto.reposicao %></td>      
        <td><%= produto.enderecamento %></td>         
        <td><%= link_to content_tag(:i, "", class: "icon-edit"), edit_produto_path(produto) %></td>
        <td><%= link_to content_tag(:i, "", class: "icon-trash"), produto, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @produtos %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @produto.codigo %>
</p>

<p>
  <strong>Codigo sericard:</strong>
  <%= @produto.codigo_sericard %>
</p>

<p>
  <strong>Orientador:</strong>
  <%= @produto.orientador %>
</p>

<p>
  <strong>Edicao:</strong>
  <%= @produto.edicao %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @produto.grade %>
</p>

<p>
  <strong>Estoque atual:</strong>
  <%= @produto.estoque_atual %>
</p>

<p>
  <strong>Reposicao:</strong>
  <%= @produto.reposicao %>
</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>