config/routes.rb
Sericard::Application.routes.draw do
  
  resources :requisicoes

  match 'produtos_entrada_path', 'produtos/entrada/', :controller => 'produtos', :action => 'entrada', :via => 'get'
  match 'produtos_saida_path', 'produtos/saida/', :controller => 'produtos', :action => 'saida', :via => 'get'
  match 'produtos_search_path','search/produtos', :controller => 'produtos', :action => 'search', :via => 'get'

  match 'search/lotes/', :controller => 'lotes', :action => 'search', :via => 'get'
  match 'lotes_finalizados_path', 'lotes/finalizados/', :controller => 'lotes', :action => 'finalizados', :via => 'get'
  match 'relatorio/:id/', :controller => 'lotes', :action => 'relatorio', :via => 'get'
  
  devise_for :funcionarios

  resources :produtos
  resources :lotes, :except => [:show]
  resources :operadoras  
  resources :funcionarios

  root :to => "lotes#index"

  

end

app/models/operadora.rb
class Operadora < ActiveRecord::Base

	has_many :lotes	         

end

app/controllers/operadoras_controller.rb
class OperadorasController < ApplicationController
  before_action :set_operadora, only: [:show, :edit, :update, :destroy]
  before_action :autoriza, except: [:show]

  def autoriza
    autorizados = [1, 2]
    redirect_to lotes_path unless autorizados.include? current_funcionario.id
  end

  # GET /operadoras
  # GET /operadoras.json
  def index
    @operadoras = Operadora.all
  end

  # GET /operadoras/1
  # GET /operadoras/1.json
  def show
    @lotes = @operadora.lotes.default_estados.default_order.page params[:page]
  end

  # GET /operadoras/new
  def new
    @operadora = Operadora.new
  end

  # GET /operadoras/1/edit
  def edit
  end

  # POST /operadoras
  # POST /operadoras.json
  def create
    @operadora = Operadora.new(operadora_params)

    respond_to do |format|
      if @operadora.save
        format.html { redirect_to @operadora, notice: 'Operadora was successfully created.' }
        format.json { render action: 'show', status: :created, location: @operadora }
      else
        format.html { render action: 'new' }
        format.json { render json: @operadora.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operadoras/1
  # PATCH/PUT /operadoras/1.json
  def update
    respond_to do |format|
      if @operadora.update(operadora_params)
        format.html { redirect_to @operadora, notice: 'Operadora was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @operadora.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operadoras/1
  # DELETE /operadoras/1.json
  def destroy
    @operadora.destroy
    respond_to do |format|
      format.html { redirect_to operadoras_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operadora
      @operadora = Operadora.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operadora_params
      params.require(:operadora).permit(:nome)
    end
end

app/helpers/operadoras_helper.rb
module OperadorasHelper
end

app/views/operadoras/_form.html.erb
<%= form_for(@operadora) do |f| %>
  <% if @operadora.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operadora.errors.count, "error") %> prohibited this operadora from being saved:</h2>

      <ul>
      <% @operadora.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operadoras/edit.html.erb
<h1>Editando operadora</h1>

<%= render 'form' %>

<%= link_to 'Show', @operadora %> |
<%= link_to 'Back', operadoras_path %>

app/views/operadoras/index.html.erb
<h1>Operadoras</h1>

<table class="table table-hover table-condensed">

  <tbody>
    <% @operadoras.each do |operadora| %>
      <tr>        
        <td><%= link_to operadora.nome, operadora %></td>
        <td><%= link_to 'Editar', edit_operadora_path(operadora) %></td>
        <td><%= link_to 'Excluir', operadora, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>

<br>

<%= link_to 'Criar Operadora', new_operadora_path %>

app/views/operadoras/new.html.erb
<h1>Cadastrar operadora</h1>

<%= render 'form' %>

<%= link_to 'Back', operadoras_path %>

app/views/operadoras/show.html.erb
<h1>Lotes da operadora <%= @operadora.nome %></h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Operadora</th>      
      <th>Colaborador</th>      
      <th>Cadastro</th>
      <th>C</th>
      <th>K</th>
      <th>Entrada</th>
      <th>Entrega</th>
      <th>Início</th>
      <th>Término</th>
      <th><i class="icon-exclamation-sign"></i></th>       
    </tr>
  </thead>

  <tbody>
    <% @lotes.each do |lote| %>
      <tr class="<%= lote.estado_to_bootstrap %>">
        <td><%= link_to lote.codigo, "/relatorio/#{lote.id}.pdf", :target => "_blank" %></td>
        <td><%= link_to lote.operadora.nome, lote.operadora %></td>
        <td><%= link_to lote.encarregado.nome, lote.encarregado %></td>
        <td><%= link_to lote.funcionario.nome, lote.funcionario %></td>        
        <td><%= lote.quantidade_cartoes %></td>
        <td><%= lote.quantidade_kits %></td>
        <td><%= lote.data_entrada.strftime("%d/%m/%y") if lote.data_entrada %></td>
        <td><%= lote.data_entrega.strftime("%d/%m/%y") if lote.data_entrega %></td>
        <td><%= lote.data_inicio.strftime("%d/%m/%y") if lote.data_inicio %></td>
        <td><%= lote.data_termino.strftime("%d/%m/%y") if lote.data_termino %></td>
        <td><%= lote.prioridade ? "Sim" : "Não" %></td>
        <td><%= link_to content_tag(:i, "", class: "icon-edit"), edit_lote_path(lote) %></td>
        <td><%= link_to content_tag(:i, "", class: "icon-trash"), lote, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @lotes %>