config/routes.rb
Sericard::Application.routes.draw do
  
  resources :requisicoes

  match 'produtos_entrada_path', 'produtos/entrada/', :controller => 'produtos', :action => 'entrada', :via => 'get'
  match 'produtos_saida_path', 'produtos/saida/', :controller => 'produtos', :action => 'saida', :via => 'get'
  match 'produtos_search_path','search/produtos', :controller => 'produtos', :action => 'search', :via => 'get'

  match 'search/lotes/', :controller => 'lotes', :action => 'search', :via => 'get'
  match 'lotes_finalizados_path', 'lotes/finalizados/', :controller => 'lotes', :action => 'finalizados', :via => 'get'
  match 'relatorio/:id/', :controller => 'lotes', :action => 'relatorio', :via => 'get'
  
  devise_for :funcionarios

  resources :produtos
  resources :lotes, :except => [:show]
  resources :operadoras  
  resources :funcionarios

  root :to => "lotes#index"

  

end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :trackable

  	validates_presence_of :nome, :password, :password_confirmation
	
	has_many :lotes_cadastrados, :class_name => "Lote", :foreign_key => "funcionario_id"
	has_many :lotes_produzidos, :class_name => "Lote", :foreign_key => "encarregado_id"
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]
  before_action :autoriza, except: [:show]

  def autoriza
    autorizados = [1, 2]
    redirect_to lotes_path unless autorizados.include? current_funcionario.id
  end

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new    
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create        

      @funcionario = Funcionario.new(funcionario_params)
      @funcionario.email = "#{Funcionario.all.size}#{Time.now.to_f}@sericard.com.br"
      
      respond_to do |format|
        if @funcionario.save
          format.html { redirect_to funcionarios_path, notice: 'Funcionario was successfully created.' }
          format.json { render action: 'show', status: :created, location: @funcionario }
        else
          format.html { render action: 'new' }
          format.json { render json: @funcionario.errors, status: :unprocessable_entity }
        end
      end      
    
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update   

      @funcionario.email = "#{@funcionario.id}@sericard.com.br"

      respond_to do |format|
        if @funcionario.update(funcionario_params)
          format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @funcionario.errors, status: :unprocessable_entity }
        end
      end
    
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy    

      @funcionario.destroy
      respond_to do |format|
        format.html { redirect_to funcionarios_url }
        format.json { head :no_content }
      end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :password, :password_confirmation)
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_for(@funcionario) do |f| %>
  <% if @funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
      <% @funcionario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, :autofocus => true %>
  </div>

  <div><label for="funcionario_password">Senha</label><br />
  <%= f.password_field :password %></div>

  <div><label for="funcionario_password_confirmation">Confirme a senha:</label><br />
  <%= f.password_field :password_confirmation %></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/funcionarios/edit.html.erb
<h1>Editando funcionario</h1>

<%= render 'form' %>

<%= link_to 'Show', @funcionario %> |
<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/index.html.erb
<h1>Funcionários</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Nome</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>        
        <td><%= link_to funcionario.nome, funcionario %></td>
        <td><%= link_to 'Editar', edit_funcionario_path(funcionario) %></td>
        <td><%= link_to 'Excluir', funcionario, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Criar Funcionario', new_funcionario_path %>

app/views/funcionarios/new.html.erb
<h1>Cadastrar funcionario</h1>

<%= render 'form' %>

<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/show.html.erb
<h1>Lotes cadastrados por <%= @funcionario.nome %></h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Operadora</th>      
      <th>Colaborador</th>      
      <th>Cadastro</th>
      <th>C</th>
      <th>K</th>
      <th>Entrada</th>
      <th>Entrega</th>
      <th>Início</th>
      <th>Término</th>
      <th><i class="icon-exclamation-sign"></i></th>       
    </tr>
  </thead>

  <tbody>
    <% @funcionario.lotes_cadastrados.default_order.each do |lote| %>
      <tr class="<%= lote.estado_to_bootstrap %>">
        <td><%= link_to lote.codigo, "/relatorio/#{lote.id}.pdf", :target => "_blank" %></td>
        <td><%= link_to lote.operadora.nome, lote.operadora %></td>
        <td><%= link_to lote.encarregado.nome, lote.encarregado %></td>
        <td><%= link_to lote.funcionario.nome, lote.funcionario %></td>        
        <td><%= lote.quantidade_cartoes %></td>
        <td><%= lote.quantidade_kits %></td>
        <td><%= lote.data_entrada.strftime("%d/%m/%y") if lote.data_entrada %></td>
        <td><%= lote.data_entrega.strftime("%d/%m/%y") if lote.data_entrega %></td>
        <td><%= lote.data_inicio.strftime("%d/%m/%y") if lote.data_inicio %></td>
        <td><%= lote.data_termino.strftime("%d/%m/%y") if lote.data_termino %></td>
        <td><%= lote.prioridade ? "Sim" : "Não" %></td>
        <td><%= link_to content_tag(:i, "", class: "icon-edit"), edit_lote_path(lote) %></td>
        <td><%= link_to content_tag(:i, "", class: "icon-trash"), lote, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Lotes produzidos por <%= @funcionario.nome %></h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Operadora</th>      
      <th>Colaborador</th>      
      <th>Cadastro</th>
      <th>C</th>
      <th>K</th>
      <th>Entrada</th>
      <th>Entrega</th>
      <th>Início</th>
      <th>Término</th>
      <th><i class="icon-exclamation-sign"></i></th>        
    </tr>
  </thead>

  <tbody>
    <% @funcionario.lotes_produzidos.estados([:atrasado, :nao_iniciado, :em_producao]).default_order.each do |lote| %>
      <tr class="<%= lote.estado_to_bootstrap %>">
        <td><%= link_to lote.codigo, "/relatorio/#{lote.id}.pdf", :target => "_blank" %></td>
        <td><%= link_to lote.operadora.nome, lote.operadora %></td>
        <td><%= link_to lote.encarregado.nome, lote.encarregado %></td>
        <td><%= link_to lote.funcionario.nome, lote.funcionario %></td>        
        <td><%= lote.quantidade_cartoes %></td>
        <td><%= lote.quantidade_kits %></td>
        <td><%= lote.data_entrada.strftime("%d/%m/%y") if lote.data_entrada %></td>
        <td><%= lote.data_entrega.strftime("%d/%m/%y") if lote.data_entrega %></td>
        <td><%= lote.data_inicio.strftime("%d/%m/%y") if lote.data_inicio %></td>
        <td><%= lote.data_termino.strftime("%d/%m/%y") if lote.data_termino %></td>
        <td><%= lote.prioridade ? "Sim" : "Não" %></td>
        <td><%= link_to content_tag(:i, "", class: "icon-edit"), edit_lote_path(lote) %></td>
        <td><%= link_to content_tag(:i, "", class: "icon-trash"), lote, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>