config/routes.rb
Sericard::Application.routes.draw do
  
  resources :requisicoes

  match 'produtos_entrada_path', 'produtos/entrada/', :controller => 'produtos', :action => 'entrada', :via => 'get'
  match 'produtos_saida_path', 'produtos/saida/', :controller => 'produtos', :action => 'saida', :via => 'get'
  match 'produtos_search_path','search/produtos', :controller => 'produtos', :action => 'search', :via => 'get'

  match 'search/lotes/', :controller => 'lotes', :action => 'search', :via => 'get'
  match 'lotes_finalizados_path', 'lotes/finalizados/', :controller => 'lotes', :action => 'finalizados', :via => 'get'
  match 'relatorio/:id/', :controller => 'lotes', :action => 'relatorio', :via => 'get'
  
  devise_for :funcionarios

  resources :produtos
  resources :lotes, :except => [:show]
  resources :operadoras  
  resources :funcionarios

  root :to => "lotes#index"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sericard - Produção Online</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-inverse navbar-fixed-top">
        
        <div class="navbar-inner">
          <div class="container">
            <ul class="nav">
                <a class="brand" href="/">Produção Online</a>                

                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Produção <b class="caret"></b></a>
                    <ul class="dropdown-menu">

                        <li class="dropdown-submenu">
                          <a tabindex="-1" href="#">Lotes</a>
                            <ul class="dropdown-menu">
                              <li><a tabindex="-1" href="<%= lotes_path %>">Todos</a></li>
                              <li><a tabindex="-1" href="<%= lotes_finalizados_path %>">Finalizados</a></li>
                              <li><a tabindex="-1" href="<%= new_lote_path %>">Adicionar Lote</a></li>
                              <li>
                                <form class="navbar-search pull-left" action="/search/lotes/" method="get">
                                  <input type="text" name="codigo" class="search-query span2" placeholder="Buscar...">
                                </form>
                              </li>
                            </ul>
                        </li>                                  

                        <li class="dropdown-submenu">
                          <a tabindex="-1" href="#">Operadoras</a>
                            <ul class="dropdown-menu">
                              <li><a tabindex="-1" href="<%= operadoras_path %>">Todos</a></li>                      
                              <li><a tabindex="-1" href="<%= new_operadora_path %>">Cadastrar Operadora</a></li>
                            </ul>
                        </li>
  
                    </li>
                  </ul>
                </li>                                  


                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Funcionários <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a tabindex="-1" href="<%= funcionarios_path %>">Todos</a></li>                      
                      <li><a tabindex="-1" href="<%= new_funcionario_path %>">Cadastrar Funcionário</a></li>
                    </ul>
                </li> 

                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Estoque <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a tabindex="-1" href="<%= produtos_path %>">Todos</a></li>
                      <li><a tabindex="-1" href="<%= new_produto_path %>">Adicionar Produto</a></li>                     
                      <li>
                        <form class="navbar-search pull-left" action="/search/produtos/" method="get">
                          <input type="text" name="codigo" class="search-query span2" placeholder="Buscar...">
                        </form>
                      </li>
                    </ul>
                </li>              
                
            </ul>

            

            <ul class="nav pull-right">

                <!-- Logout or Sign in/Sign up -->
                <% if funcionario_signed_in? %>
                  <li><%= link_to current_funcionario.nome, funcionario_path(current_funcionario) %></li>
                  <li><%= link_to 'Sair', destroy_funcionario_session_path, :method => :delete %></li>
                <% end %>
                <!-- Logout or Sign in/Sign up -->

            </ul>

          </div>
        </div>



    </div>

    <div class="container container-fluid main-container">

      	<div class="row row-fluid">
	        <div class="span12">
	            <%= yield %>
	        </div>
      	</div>

    </div>


</body>
</html>